---
abstract: 'nested hashref serializable to the file'
author:
  - 'Vyacheslav Matyukhin <me@berekuk.ru>'
  - 'Andrei Mishchenko <druxa@yandex-team.ru>'
  - 'Artyom V. Kulikov <breqwas@yandex-team.ru>'
build_requires:
  IPC::System::Simple: 0
  Test::Fatal: 0
  Test::More: 0.95
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-Persistent
requires:
  Carp: 0
  Data::Dumper: 0
  JSON: 0
  Lock::File: 1.01
  Storable: 0
  autodie: 0
  strict: 0
  warnings: 0
version: 1.00
